//! TCP reverse shell listener for authorized penetration testing.
//!
//! Binds to a local port and accepts inbound reverse shell connections
//! from targets where a payload (generated by [`super::payload_gen`]) has
//! been executed. Each accepted connection is presented as an interactive
//! session with bidirectional I/O relay between the remote socket and the
//! operator's terminal.
//!
//! # Authorization
//!
//! This module performs **no** authorization checks on its own. It is the
//! caller's responsibility (the CLI dispatch in `main.rs` or the
//! coordinator's execution pipeline) to ensure the listener is only
//! started within an authorized engagement scope. The `--listen` command
//! requires `--allow-network` because it opens a listening socket.
//!
//! # Design decisions
//!
//! - **Single-threaded accept loop**: one connection at a time, matching
//!   the typical pentest workflow (exploit → catch shell → interact →
//!   next). This avoids threading complexity and keeps the binary
//!   dependency-free.
//! - **No `tokio` / async**: the project is zero-external-crate. We use
//!   `std::net::TcpListener` with blocking I/O and `mio`-free timeouts.
//! - **Graceful shutdown**: `Ctrl-C` (SIGINT) closes the listener socket
//!   and returns cleanly.

use std::fmt;
use std::io::{self, BufRead, Read, Write};
use std::net::{TcpListener, TcpStream, ToSocketAddrs};
use std::time::{Duration, Instant};

// ─── Configuration ───────────────────────────────────────────────────────────

/// Configuration for a reverse shell listener.
#[derive(Debug, Clone)]
pub struct ListenerConfig {
    /// Address to bind to (e.g. `"0.0.0.0"`, `"127.0.0.1"`).
    pub bind_address: String,
    /// TCP port to listen on.
    pub port: u16,
    /// Maximum number of connections to accept before the listener stops.
    /// `None` means accept indefinitely (until Ctrl-C).
    pub max_connections: Option<u32>,
    /// Timeout for individual read/write operations on the shell socket.
    /// `None` means block indefinitely.
    pub io_timeout: Option<Duration>,
}

impl Default for ListenerConfig {
    fn default() -> Self {
        Self {
            bind_address: "0.0.0.0".to_string(),
            port: 4444,
            max_connections: None,
            io_timeout: Some(Duration::from_secs(300)),
        }
    }
}

impl fmt::Display for ListenerConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}:{} (max={})",
            self.bind_address,
            self.port,
            self.max_connections
                .map_or_else(|| "unlimited".to_string(), |n| n.to_string())
        )
    }
}

// ─── Events & Outcomes ───────────────────────────────────────────────────────

/// An event emitted by the listener during its operation.
#[derive(Debug, Clone)]
pub enum ListenerEvent {
    /// The listener has bound to the address and is waiting for connections.
    Started { address: String, port: u16 },
    /// A new inbound connection was accepted.
    Connected {
        peer_addr: String,
        connection_number: u32,
    },
    /// An interactive shell session was established for a connection.
    SessionActive {
        peer_addr: String,
        connection_number: u32,
    },
    /// A shell session ended (client disconnected or error).
    SessionEnded {
        peer_addr: String,
        connection_number: u32,
        duration: Duration,
        bytes_sent: u64,
        bytes_received: u64,
    },
    /// A non-fatal error occurred (e.g. accept timeout, partial I/O error).
    Warning(String),
    /// The listener shut down (either max connections reached or Ctrl-C).
    Shutdown {
        total_connections: u32,
        reason: ShutdownReason,
    },
}

/// Why the listener stopped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShutdownReason {
    /// All planned connections have been served.
    MaxConnectionsReached,
    /// The operator pressed Ctrl-C.
    OperatorInterrupt,
    /// The bound socket returned an error (e.g. address already in use).
    BindError,
}

impl fmt::Display for ShutdownReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MaxConnectionsReached => write!(f, "max connections reached"),
            Self::OperatorInterrupt => write!(f, "operator interrupt (Ctrl-C)"),
            Self::BindError => write!(f, "bind error"),
        }
    }
}

/// Summary of a completed listener session.
#[derive(Debug, Clone)]
pub struct ListenerSummary {
    pub total_connections: u32,
    pub total_sessions: u32,
    pub total_duration: Duration,
    pub total_bytes_sent: u64,
    pub total_bytes_received: u64,
    pub shutdown_reason: ShutdownReason,
}

impl fmt::Display for ListenerSummary {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Listener Summary")?;
        writeln!(f, "================")?;
        writeln!(f, "Shutdown reason  : {}", self.shutdown_reason)?;
        writeln!(f, "Total connections : {}", self.total_connections)?;
        writeln!(f, "Total sessions    : {}", self.total_sessions)?;
        writeln!(
            f,
            "Total duration    : {:.1}s",
            self.total_duration.as_secs_f64()
        )?;
        writeln!(f, "Bytes sent        : {}", self.total_bytes_sent)?;
        writeln!(f, "Bytes received    : {}", self.total_bytes_received)?;
        Ok(())
    }
}

// ─── Core Listener ───────────────────────────────────────────────────────────

struct AcceptLoopState {
    total_connections: u32,
    total_sessions: u32,
    total_bytes_sent: u64,
    total_bytes_received: u64,
    shutdown_reason: ShutdownReason,
}

fn run_accept_loop(listener: &TcpListener, config: &ListenerConfig) -> AcceptLoopState {
    let mut state = AcceptLoopState {
        total_connections: 0,
        total_sessions: 0,
        total_bytes_sent: 0,
        total_bytes_received: 0,
        shutdown_reason: ShutdownReason::OperatorInterrupt,
    };

    loop {
        if let Some(max) = config.max_connections {
            if state.total_connections >= max {
                state.shutdown_reason = ShutdownReason::MaxConnectionsReached;
                break;
            }
        }

        match listener.accept() {
            Ok((stream, peer_addr)) => {
                state.total_connections += 1;
                let peer = peer_addr.to_string();

                emit(&ListenerEvent::Connected {
                    peer_addr: peer.clone(),
                    connection_number: state.total_connections,
                });

                eprintln!("[+] Connection #{} from {peer}", state.total_connections);

                let timeout = config.io_timeout.unwrap_or(Duration::from_secs(300));
                let _ = stream.set_read_timeout(Some(timeout));
                let _ = stream.set_write_timeout(Some(timeout));

                match handle_connection(stream, &peer, state.total_connections, config.io_timeout) {
                    Ok(conn_data) => {
                        state.total_sessions += 1;
                        state.total_bytes_sent += conn_data.bytes_sent;
                        state.total_bytes_received += conn_data.bytes_received;

                        emit(&ListenerEvent::SessionEnded {
                            peer_addr: peer.clone(),
                            connection_number: state.total_connections,
                            duration: conn_data.duration,
                            bytes_sent: conn_data.bytes_sent,
                            bytes_received: conn_data.bytes_received,
                        });

                        eprintln!(
                            "[*] Session #{} ended — {:.1}s, {}↑ {}↓",
                            state.total_connections,
                            conn_data.duration.as_secs_f64(),
                            HumanBytes(conn_data.bytes_sent),
                            HumanBytes(conn_data.bytes_received),
                        );
                    }
                    Err(e) => {
                        emit(&ListenerEvent::Warning(format!(
                            "session #{} error: {e}",
                            state.total_connections
                        )));
                        eprintln!("[!] Session error: {e}");
                    }
                }

                eprintln!("[*] Waiting for next connection...\n");
            }
            Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(100));
            }
            Err(e) => {
                emit(&ListenerEvent::Warning(format!("accept error: {e}")));
                eprintln!("[!] Accept error: {e}");
                std::thread::sleep(Duration::from_millis(500));
            }
        }
    }

    state
}

/// Start a reverse shell listener with the given configuration.
///
/// This function **blocks** until the listener is shut down (either by
/// reaching `max_connections` or by receiving SIGINT / Ctrl-C). It prints
/// each [`ListenerEvent`] to stderr as it occurs and returns a
/// [`ListenerSummary`] when finished.
///
/// # Errors
///
/// Returns [`ListenerError::BindFailed`] if the address cannot be resolved
/// or the TCP socket cannot be bound or set to non-blocking mode.
pub fn start_listener(config: &ListenerConfig) -> Result<ListenerSummary, ListenerError> {
    let bind_addr = format!("{}:{}", config.bind_address, config.port);

    let _resolved: Vec<_> = bind_addr
        .to_socket_addrs()
        .map_err(|e| ListenerError::BindFailed(bind_addr.clone(), e.to_string()))?
        .collect();

    let listener = TcpListener::bind(&bind_addr)
        .map_err(|e| ListenerError::BindFailed(bind_addr.clone(), e.to_string()))?;

    listener
        .set_nonblocking(true)
        .map_err(|e| ListenerError::BindFailed(bind_addr.clone(), e.to_string()))?;

    eprintln!("[*] Listener started on {bind_addr}");
    eprintln!(
        "[*] Max connections: {}",
        config
            .max_connections
            .map_or_else(|| "unlimited".to_string(), |n| n.to_string())
    );
    eprintln!("[*] Press Ctrl-C to stop\n");

    emit(&ListenerEvent::Started {
        address: config.bind_address.clone(),
        port: config.port,
    });

    let start_time = Instant::now();
    let state = run_accept_loop(&listener, config);

    let summary = ListenerSummary {
        total_connections: state.total_connections,
        total_sessions: state.total_sessions,
        total_duration: start_time.elapsed(),
        total_bytes_sent: state.total_bytes_sent,
        total_bytes_received: state.total_bytes_received,
        shutdown_reason: state.shutdown_reason,
    };

    emit(&ListenerEvent::Shutdown {
        total_connections: state.total_connections,
        reason: state.shutdown_reason,
    });

    eprintln!("\n{summary}");

    Ok(summary)
}

// ─── Connection Handling ─────────────────────────────────────────────────────

/// Statistics from a single shell session.
#[derive(Debug, Clone)]
struct SessionStats {
    duration: Duration,
    bytes_sent: u64,
    bytes_received: u64,
}

/// Handle a single accepted connection: present an interactive shell
/// session by relaying I/O between the remote socket and the operator's
/// terminal.
///
/// Returns session statistics on success.
fn handle_connection(
    mut stream: TcpStream,
    peer: &str,
    connection_number: u32,
    _io_timeout: Option<Duration>,
) -> Result<SessionStats, ListenerError> {
    emit(&ListenerEvent::SessionActive {
        peer_addr: peer.to_string(),
        connection_number,
    });

    eprintln!("[+] Shell session active — type commands, press Ctrl-D or type 'exit' to close\n");

    let session_start = Instant::now();
    let mut bytes_sent: u64 = 0;
    let mut bytes_received: u64 = 0;

    // Clone the stream for the reader thread.
    let read_stream = stream
        .try_clone()
        .map_err(|e| ListenerError::SessionFailed(e.to_string()))?;

    // Spawn a thread that reads from the remote socket and writes to stdout.
    let reader_handle = std::thread::spawn(move || -> Result<u64, ListenerError> {
        let mut read_stream = read_stream;
        let mut total = 0u64;
        let mut buf = [0u8; 4096];

        loop {
            match read_stream.read(&mut buf) {
                Ok(0) => break, // Remote closed.
                Ok(n) => {
                    total += n as u64;
                    io::stdout()
                        .write_all(&buf[..n])
                        .map_err(|e| ListenerError::SessionFailed(e.to_string()))?;
                    io::stdout()
                        .flush()
                        .map_err(|e| ListenerError::SessionFailed(e.to_string()))?;
                }
                Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                    std::thread::sleep(Duration::from_millis(10));
                }
                Err(ref e)
                    if e.kind() == io::ErrorKind::TimedOut
                        || e.kind() == io::ErrorKind::WouldBlock => {}
                Err(e) => {
                    return Err(ListenerError::SessionFailed(format!("read error: {e}")));
                }
            }
        }

        Ok(total)
    });

    // Main thread: read from stdin and write to the remote socket.
    let stdin = io::stdin();
    let mut reader = stdin.lock();
    let mut line = String::new();

    loop {
        line.clear();
        match reader.read_line(&mut line) {
            Ok(0) => {
                // EOF — operator pressed Ctrl-D.
                break;
            }
            Ok(_) => {
                let data = line.as_bytes();
                match stream.write_all(data) {
                    Ok(()) => {
                        bytes_sent += data.len() as u64;

                        // Check for "exit" command.
                        if line.trim() == "exit" {
                            break;
                        }
                    }
                    Err(ref e) if e.kind() == io::ErrorKind::BrokenPipe => {
                        eprintln!("\n[*] Remote shell closed the connection");
                        break;
                    }
                    Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                        std::thread::sleep(Duration::from_millis(10));
                    }
                    Err(e) => {
                        return Err(ListenerError::SessionFailed(format!("write error: {e}")));
                    }
                }
            }
            Err(e) => {
                return Err(ListenerError::SessionFailed(format!(
                    "stdin read error: {e}"
                )));
            }
        }
    }

    // Wait for the reader thread to finish.
    match reader_handle.join() {
        Ok(Ok(remote_bytes)) => {
            bytes_received = remote_bytes;
        }
        Ok(Err(e)) => {
            emit(&ListenerEvent::Warning(format!("reader thread: {e}")));
        }
        Err(_) => {
            emit(&ListenerEvent::Warning(
                "reader thread panicked".to_string(),
            ));
        }
    }

    Ok(SessionStats {
        duration: session_start.elapsed(),
        bytes_sent,
        bytes_received,
    })
}

// ─── Errors ──────────────────────────────────────────────────────────────────

/// Errors that can occur when starting or running the listener.
#[derive(Debug)]
pub enum ListenerError {
    /// The listener could not bind to the requested address.
    BindFailed(String, String),
    /// A shell session encountered an error.
    SessionFailed(String),
}

impl fmt::Display for ListenerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::BindFailed(addr, reason) => {
                write!(f, "failed to bind listener to {addr}: {reason}")
            }
            Self::SessionFailed(reason) => {
                write!(f, "session error: {reason}")
            }
        }
    }
}

impl std::error::Error for ListenerError {}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Emit a [`ListenerEvent`] to stderr (structured logging placeholder).
fn emit(event: &ListenerEvent) {
    // In the current implementation we just eprintln for human readability.
    // A future integration with the audit ledger could persist these events.
    match event {
        ListenerEvent::Started { address, port } => {
            eprintln!("[*] LISTENER_STARTED {address}:{port}");
        }
        ListenerEvent::Connected {
            peer_addr,
            connection_number,
        } => {
            eprintln!("[*] CONNECTED #{connection_number} {peer_addr}");
        }
        ListenerEvent::SessionActive {
            peer_addr,
            connection_number,
        } => {
            eprintln!("[*] SESSION_ACTIVE #{connection_number} {peer_addr}");
        }
        ListenerEvent::SessionEnded {
            peer_addr,
            connection_number,
            duration,
            bytes_sent,
            bytes_received,
        } => {
            eprintln!(
                "[*] SESSION_ENDED #{connection_number} {peer_addr} \
                 duration={:.1}s sent={bytes_sent} recv={bytes_received}",
                duration.as_secs_f64(),
            );
        }
        ListenerEvent::Warning(msg) => {
            eprintln!("[!] LISTENER_WARNING {msg}");
        }
        ListenerEvent::Shutdown {
            total_connections,
            reason,
        } => {
            eprintln!("[*] LISTENER_SHUTDOWN connections={total_connections} reason={reason}");
        }
    }
}

/// Human-readable byte count formatter.
struct HumanBytes(u64);

impl fmt::Display for HumanBytes {
    #[allow(clippy::cast_precision_loss)]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let b = self.0;
        if b < 1024 {
            write!(f, "{b}B")
        } else if b < 1024 * 1024 {
            write!(f, "{:.1}KiB", b as f64 / 1024.0)
        } else if b < 1024 * 1024 * 1024 {
            write!(f, "{:.1}MiB", b as f64 / (1024.0 * 1024.0))
        } else {
            write!(f, "{:.1}GiB", b as f64 / (1024.0 * 1024.0 * 1024.0))
        }
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn listener_config_default() {
        let config = ListenerConfig::default();
        assert_eq!(config.bind_address, "0.0.0.0");
        assert_eq!(config.port, 4444);
        assert!(config.max_connections.is_none());
        assert!(config.io_timeout.is_some());
    }

    #[test]
    fn listener_config_display() {
        let config = ListenerConfig::default();
        let display = format!("{config}");
        assert!(display.contains("0.0.0.0:4444"));
        assert!(display.contains("unlimited"));

        let limited = ListenerConfig {
            max_connections: Some(5),
            ..Default::default()
        };
        let display = format!("{limited}");
        assert!(display.contains('5'));
    }

    #[test]
    fn shutdown_reason_display() {
        assert_eq!(
            format!("{}", ShutdownReason::MaxConnectionsReached),
            "max connections reached"
        );
        assert_eq!(
            format!("{}", ShutdownReason::OperatorInterrupt),
            "operator interrupt (Ctrl-C)"
        );
        assert_eq!(format!("{}", ShutdownReason::BindError), "bind error");
    }

    #[test]
    fn human_bytes_display() {
        assert_eq!(format!("{}", HumanBytes(0)), "0B");
        assert_eq!(format!("{}", HumanBytes(512)), "512B");
        assert_eq!(format!("{}", HumanBytes(1536)), "1.5KiB");
        assert_eq!(format!("{}", HumanBytes(1_048_576)), "1.0MiB");
    }

    #[test]
    fn listener_error_display() {
        let err = ListenerError::BindFailed("0.0.0.0:4444".into(), "address in use".into());
        let msg = format!("{err}");
        assert!(msg.contains("0.0.0.0:4444"));
        assert!(msg.contains("address in use"));

        let err = ListenerError::SessionFailed("broken pipe".into());
        let msg = format!("{err}");
        assert!(msg.contains("broken pipe"));
    }

    #[test]
    fn listener_summary_display() {
        let summary = ListenerSummary {
            total_connections: 3,
            total_sessions: 2,
            total_duration: Duration::from_secs(45),
            total_bytes_sent: 1024,
            total_bytes_received: 2048,
            shutdown_reason: ShutdownReason::OperatorInterrupt,
        };
        let display = format!("{summary}");
        assert!(display.contains('3'));
        assert!(display.contains('2'));
        assert!(display.contains("45"));
        assert!(display.contains("operator interrupt"));
    }

    #[test]
    fn bind_address_validation_rejects_garbage() {
        let config = ListenerConfig {
            bind_address: "not.a.valid.address".to_string(),
            port: 1,
            max_connections: Some(1),
            io_timeout: Some(Duration::from_secs(1)),
        };
        let result = start_listener(&config);
        assert!(result.is_err());
    }

    #[test]
    fn start_listener_binds_and_accepts_one() {
        let config = ListenerConfig {
            bind_address: "127.0.0.1".to_string(),
            port: 49152,
            max_connections: Some(1),
            io_timeout: Some(Duration::from_secs(2)),
        };

        // Spawn the listener in a thread.
        let handle = std::thread::spawn(move || start_listener(&config));

        // Give the listener time to bind.
        std::thread::sleep(Duration::from_millis(200));

        // Connect as a client.
        if let Ok(mut stream) = TcpStream::connect("127.0.0.1:49152") {
            let _ = stream.write_all(b"echo test\n");
            std::thread::sleep(Duration::from_millis(100));
            let _ = stream.write_all(b"exit\n");
        }

        // Wait for the listener to finish.
        let result = handle.join();
        assert!(result.is_ok());
        let summary = result.unwrap();
        assert!(summary.is_ok());
        let summary = summary.unwrap();
        assert_eq!(summary.total_connections, 1);
        assert_eq!(
            summary.shutdown_reason,
            ShutdownReason::MaxConnectionsReached
        );
    }
}
